# Generated by Django 4.2.26 on 2025-11-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_portfolioinfo_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=200)),
                ("program", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("graduation_year", models.IntegerField()),
            ],
            options={
                "ordering": ["-graduation_year"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if currently working here",
                        null=True,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        blank=True, help_text="Client title or company", max_length=200
                    ),
                ),
                ("quote", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 stars"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ],
                        default=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                blank=True, help_text="e.g., Web, Mobile, Design", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
    ]
