# Generated by Django 4.2.26 on 2025-11-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0003_education_experience_testimonial_project_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioinfo",
            name="email_primary",
            field=models.EmailField(
                blank=True, default="Aldrinjadesaura11@gmail.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="portfolioinfo",
            name="email_secondary",
            field=models.EmailField(
                blank=True, default="aldrinjade.s11@yahoo.com", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="portfolioinfo",
            name="facebook",
            field=models.CharField(blank=True, default="Aljin Gc", max_length=200),
        ),
        migrations.AddField(
            model_name="portfolioinfo",
            name="instagram",
            field=models.CharField(
                blank=True, default="Aldrin jade saura", max_length=200
            ),
        ),
    ]
