# Generated by Django 4.2.26 on 2025-11-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_portfolioinfo_email_primary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class or emoji",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Technologies",
            },
        ),
        migrations.AddField(
            model_name="portfolioinfo",
            name="bio",
            field=models.TextField(
                blank=True,
                default="Creative developer passionate about building web and game projects",
            ),
        ),
        migrations.AddField(
            model_name="portfolioinfo",
            name="github",
            field=models.URLField(blank=True, help_text="GitHub profile URL"),
        ),
        migrations.AddField(
            model_name="portfolioinfo",
            name="linkedin",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL"),
        ),
        migrations.AddField(
            model_name="portfolioinfo",
            name="twitter",
            field=models.URLField(blank=True, help_text="Twitter profile URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select technologies used",
                to="portfolio.technology",
            ),
        ),
    ]
