# Generated by Django 4.2.26 on 2025-11-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0005_technology_portfolioinfo_bio_portfolioinfo_github_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("email_primary", models.EmailField(blank=True, max_length=254)),
                ("email_secondary", models.EmailField(blank=True, max_length=254)),
                ("facebook", models.CharField(blank=True, max_length=200)),
                ("instagram", models.CharField(blank=True, max_length=200)),
                ("github", models.URLField(blank=True, help_text="GitHub profile URL")),
                (
                    "linkedin",
                    models.URLField(blank=True, help_text="LinkedIn profile URL"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, help_text="Twitter profile URL"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select skills for this person",
                        to="portfolio.skill",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "People",
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="PortfolioInfo",
        ),
    ]
