# Generated by Django 4.2.26 on 2025-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_person_delete_portfolioinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a profile photo', null=True, upload_to='team/'),
        ),
    ]
