# Generated by Django 5.2.8 on 2025-11-30 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_person_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-graduation_year'], 'verbose_name_plural': 'Education'},
        ),
        migrations.AddField(
            model_name='education',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='portfolio.person'),
        ),
        migrations.AddField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.person'),
        ),
    ]
